const UI_COLORS ={
  APP_BACKGROUND:'#FFE600',
  PRODUCT_LIST_HEADER_BACKGROUND:'black',
  CARD_VIEW_PRODUCT_BACKGROUND:'#D9D9D9',
  DESCRIPTION_BTN_BACKGROUND:'#FF9292',
  BUY_BTN_BACKGROUND:'#05FF00',
  NAV_STACK_PRODUCT_LIST_BACKGROUND:'black'
}
export default UI_COLORS;